-- 코드를 입력하세요
SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK
WHERE CATEGORY = '인문' AND DATE_FORMAT(PUBLISHED_DATE, '%Y-%m') BETWEEN '2021-01' AND '2021-12'
ORDER BY PUBLISHED_DATE ASC