SELECT gds.TITLE, gds.BOARD_ID, repl.REPLY_ID, repl.WRITER_ID, repl.CONTENTS, DATE_FORMAT(repl.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD gds JOIN USED_GOODS_REPLY repl ON gds.BOARD_ID = repl.BOARD_ID
WHERE YEAR(gds.CREATED_DATE) = 2022 AND MONTH(gds.CREATED_DATE) = 10
ORDER BY repl.CRE ASC, gds.TITLE ASC;