-- 코드를 입력하세요
SELECT B.title TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE,"%Y-%m-%d") as 'CREATED_DATE'
from USED_GOODS_BOARD B inner join USED_GOODS_REPLY R on B.BOARD_ID = R.BOARD_ID
WHERE B.CREATED_DATE >= '2022-10-01' and B.CREATED_DATE < '2022-11-01'
order by R.CREATED_DATE, B.TITLE;
